[package]
name = "jaq-parse"
version = "0.6.0"
authors = ["Michael FÃ¤rber <michael.faerber@gedenkt.at>"]
edition = "2021"
license = "MIT"
readme = "../README.md"
description = "Parser for the jaq language"
repository = "https://github.com/01mf02/jaq"
keywords = ["json", "query", "jq"]
categories = ["parser-implementations"]

[features]
default = ["serde"]

[dependencies]
chumsky = "0.8.0"
serde = { version = "1.0.137", features = ["derive"], optional = true }
