name: Generate documentation and run unit tests

on:
  push:
    branches: [ main ]
    paths:
      - 'docs'
  pull_request:
    branches: [ main ]

jobs:
  check:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - name: Install jotdown
      run: cargo install jotdown@0.8.1 --locked
    - name: Generate documentation and run unit tests
      working-directory: docs
      run: make JAQ=`cargo --quiet --config "target.'cfg(true)'.runner = 'echo'" run` MANUAL.xhtml tests cli-tests
    - uses: actions/upload-artifact@v4
      with:
        name: docs
        path: docs/MANUAL.html
